services:
  - type: web
    name: u-mas-web
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn student_management_system.wsgi:application"
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: u-mas-db
          property: connectionString
      - key: DJANGO_ALLOWED_HOSTS
        value: "localhost,127.0.0.1" # Render external hostname added automatically in settings.py

databases:
  - name: u-mas-db
    plan: free
