services:
  - type: web
    name: u-mas
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn student_management_system.wsgi:application --bind 0.0.0.0:$PORT --workers=2 --threads=4 --timeout=120
    healthCheckPath: /testurl/
    autoDeployTrigger: commit
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: RECAPTCHA_SECRET_KEY
        sync: false
      - key: RECAPTCHA_SITE_KEY
        sync: false
      - key: RECAPTCHA_MIN_SCORE
        value: "0.5"
