# Generated by Django 4.2.28 on 2026-02-14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student_management_app", "0006_alter_customuser_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlineclassroom",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="onlineclassroom",
            name="last_board_snapshot",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="onlineclassroom",
            name="realtime_room_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="onlineclassroom",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "ACTIVE"), ("ENDED", "ENDED")],
                default="ACTIVE",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="onlineclassroom",
            name="ended_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ended_live_classes",
                to="student_management_app.staffs",
            ),
        ),
        migrations.CreateModel(
            name="LiveClassParticipant",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("role", models.CharField(choices=[("STAFF", "STAFF"), ("STUDENT", "STUDENT")], max_length=16)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("is_publisher", models.BooleanField(default=False)),
                ("room", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="participants", to="student_management_app.onlineclassroom")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="student_management_app.customuser")),
            ],
        ),
        migrations.AddIndex(
            model_name="liveclassparticipant",
            index=models.Index(fields=["room", "role"], name="live_room_role_idx"),
        ),
        migrations.AddIndex(
            model_name="liveclassparticipant",
            index=models.Index(fields=["user", "joined_at"], name="live_user_joined_idx"),
        ),
    ]
