# Generated by Django 4.2.28 on 2026-03-10 05:26

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


def normalize_emails_and_backfill_profile_ids(apps, schema_editor):
    CustomUser = apps.get_model("student_management_app", "CustomUser")
    AdminHOD = apps.get_model("student_management_app", "AdminHOD")
    Staffs = apps.get_model("student_management_app", "Staffs")
    Students = apps.get_model("student_management_app", "Students")

    seen = {}
    for user in CustomUser.objects.all().only("id", "email"):
        normalized = (user.email or "").strip().lower()
        if normalized in seen and normalized:
            raise RuntimeError(
                f"Duplicate email detected after lowercase normalization: "
                f"user #{seen[normalized]} and user #{user.id}"
            )
        seen[normalized] = user.id
        if user.email != normalized:
            user.email = normalized
            user.save(update_fields=["email"])

    for hod in AdminHOD.objects.all().only("id", "profile_id"):
        if not hod.profile_id:
            hod.profile_id = f"HOD{hod.id:05d}"
            hod.save(update_fields=["profile_id"])

    for staff in Staffs.objects.all().only("id", "profile_id"):
        if not staff.profile_id:
            staff.profile_id = f"STF{staff.id:05d}"
            staff.save(update_fields=["profile_id"])

    for student in Students.objects.all().only("id", "profile_id"):
        if not student.profile_id:
            student.profile_id = f"STD{student.id:05d}"
            student.save(update_fields=["profile_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_live_class_upgrade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddField(
            model_name='adminhod',
            name='profile_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='profile_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to='student_management_app.staffs'),
        ),
        migrations.AddField(
            model_name='students',
            name='profile_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(normalize_emails_and_backfill_profile_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='adminhod',
            name='profile_id',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='profile_id',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='profile_id',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='customuser_email_ci_unique'),
        ),
    ]
