# Generated by Django 4.2.28 on 2026-03-10 06:40

from django.db.models import Count
from django.db import migrations, models


def deduplicate_attendance_by_subject_date(apps, schema_editor):
    Attendance = apps.get_model("student_management_app", "Attendance")
    AttendanceReport = apps.get_model("student_management_app", "AttendanceReport")

    duplicates = (
        Attendance.objects.values("subject_id", "attendance_date")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
    )

    for dup in duplicates:
        records = list(
            Attendance.objects.filter(
                subject_id=dup["subject_id"],
                attendance_date=dup["attendance_date"],
            ).order_by("id")
        )
        canonical = records[0]
        for duplicate_attendance in records[1:]:
            reports = AttendanceReport.objects.filter(attendance_id=duplicate_attendance.id)
            for report in reports:
                existing = AttendanceReport.objects.filter(
                    attendance_id=canonical.id,
                    student_id=report.student_id,
                ).first()
                if existing is None:
                    report.attendance_id = canonical.id
                    report.save(update_fields=["attendance_id"])
                else:
                    if report.status and not existing.status:
                        existing.status = True
                        existing.save(update_fields=["status"])
                    report.delete()
            duplicate_attendance.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_alter_customuser_options_adminhod_profile_id_and_more'),
    ]

    operations = [
        migrations.RunPython(deduplicate_attendance_by_subject_date, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('subject_id', 'attendance_date'), name='attendance_unique_subject_date'),
        ),
    ]
