# Generated by Django 4.2.28 on 2026-04-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0009_attendance_attendance_unique_subject_date'),
        ('student_management_app', '0010_notification_titles'),
    ]

    operations = [
    ]
