# Generated by Django 4.2.30 on 2026-04-26 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0016_classmodel_collegeadmin_department_hod_institution_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='semestermodel',
            managers=[
            ],
        ),
    ]
